config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/index'

  get 'prescriptions/show'

  get 'prescriptions/create'

  get 'prescriptions/edit'

  root 'main#index'

  get "/main/settings"
  get "/select_report" => "main#select_report"
  post "/main/dispensation_report"
  post "/main/prescription_report"
  post "/main/stores_report"
  get "/time" => "main#time"

  get "/drug/search"
  get "/void_drug/:id" => "drug#destroy"
  post "/edit_drug" => "drug#edit"

  get "/void_general_inventory/:id" => "general_inventory#destroy"
  post "/void_general_inventory" => "general_inventory#destroy"
  post "/edit_general_inventory" => "general_inventory#edit"
  get "/general_inventory/expired_items"
  get "/general_inventory/expiring_items"
  get "/general_inventory/understocked"
  get "/general_inventory/wellstocked"
  get "view_gn_drug/:id" => "general_inventory#view_drug"
  get "/print_bottle_barcode/:id" => "general_inventory#print_bottle_barcode"
  get "/ajax_bottle/:id" => "general_inventory#ajax_bottle"
  get "/general_inventory/print_bottle_barcode"

  get "/username_availability" => "user#username_availability"

  get "/query_users" => "user#query"
  get "/void_user/:id" => "user#destroy"
  post "/edit_user" => "user#edit"
  get "/user/users_names"

  get "/void_prescriptions/:id" => "prescription#destroy"
  get "/prescriptions" => "prescription#ajax_prescriptions"
  post "/prescription/dispense"
  post "/prescription/edit"

  get "/print_dispensation_label/:id" => "dispensation#print_dispensation_label"
  get "/void_dispensation/:id" => "dispensation#destroy"
  

  get "/void_mobile_visit/:id" => "mobile_visit#destroy"

  get "/void_mobile_visit_product/:id" => "mobile_visit_product#destroy"

  resources :mobile_visit
  resources :mobile_visit_product
  resources :drug_threshold
  resources :prescriptions
  resources :drug
  resources :patient_identifiers

  resources :general_inventory do
    post 'pre_packing'
    collection do
      get 'print_pre_packed(/:id)', action: :print_pre_packed
      get 'list'
      post 'merge'
    end
  end

  resources :patients do
    collection do
      get 'given_names'
      get 'family_names'
    end
  end

  resources :user do
    collection do
      get 'roles'
    end
  end

  resources :dispensation do
    collection do
      post 'refill'
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
      get 'suggestions'
    end
  end

  resources :issues do
    collection do
      get 'select'
      post 'list'
    end
  end

  resources :sessions do
    collection do
      post 'login' , action: :create
      get 'logout' , action: :destroy
      get 'add_location'
      post 'workstation_location'
    end
  end
end

app/models/mobile_visit.rb
class MobileVisit < ActiveRecord::Base

  has_many :mobile_visit_products
  belongs_to :user, :foreign_key => :visit_supervisor

  validates_presence_of :visit_date
  validates_presence_of :visit_supervisor

  def coordinator
      self.user.display_name
  end

  def products
    products = MobileVisitProduct.where("voided = ? and mobile_visit_id = ?", false, self.id).length
  end
end

app/controllers/mobile_visit_controller.rb
class MobileVisitController < ApplicationController

  def index
    @visits = MobileVisit.where("voided = ? ", false).order(visit_date: :desc)
  end

  def new
    render :layout => "touch"
  end

  def show
    @visit = MobileVisit.find(params[:id])
    @visit_products = view_context.list_products(MobileVisitProduct.where("voided = ? and mobile_visit_id = ?",false,params[:id]))
  end

  def create

    coordinator = User.select("user_id , CONCAT(COALESCE(first_name,''),COALESCE(middle_name,''),
                                COALESCE(fathers_name,''),COALESCE(mothers_name,'')) as username").where("voided =?", false, ).having("username = ?", params[:visit_coordinator].gsub(" ","")).first rescue nil

    @new_visit = MobileVisit.where(visit_date: params[:visit_date].to_date, visit_supervisor: coordinator.id,voided: false).first_or_initialize

    @new_visit.save if @new_visit.id.blank?

    if @new_visit.errors.blank?
      redirect_to "/mobile_visit/#{@new_visit.id}" and return
    else
      flash[:errors] = "Mobile visit could not be created"
      redirect_to "/mobile_visit" and return
    end
  end

  def edit
    @visit = MobileVisit.find(params[:id])
    @coordinators = User.where("voided = ? AND role in (?)", false, ["administrator","Pharmacist"]).collect{|x|[x.id,x.fullname]}
    render :layout => "touch"
  end

  def update
    @new_visit = MobileVisit.find(params[:id])
    @new_visit.update_attributes(visit_date: params[:visit_date].to_date, visit_supervisor: params[:visit_coordinator].to_i)
    redirect_to "/mobile_visit" and return
  end

  def destroy
    void_visit = MobileVisit.find(params[:id])

    MobileVisit.transaction do

      void_visit.update_attributes(:voided => true)

      products = MobileVisitProduct.where("voided = ? and mobile_visit_id = ?", false, void_visit.id)

      (products || []).each do |product|

        product.voided = true
        product.save

        item = GeneralInventory.where("gn_identifier = ? AND voided = ?", product.gn_identifier, false).first

        next if item.blank?

        item.current_quantity += product.amount_used
        item.save

      end
    end

    redirect_to "/mobile_visit" and return
  end
end

app/helpers/mobile_visit_helper.rb
module MobileVisitHelper
  def list_products(items)
    products = []
    (items || []).each do |item|
      gn_item = GeneralInventory.find_by_gn_identifier(item.gn_identifier)
      next if gn_item.blank?
      products << {"product" => gn_item.drug_name, "exp_date" => gn_item.expiration_date,"id" => item.id,"voidable" => item.voidable,
        "amount_taken" => item.amount_taken, "amount_used" => item.amount_used, "bottle_id" => item.gn_identifier}
    end
    return products
  end
end

app/views/mobile_visit/edit.html.erb
<script>
  var tt_cancel_destination = "/mobile_visit";
</script>

<%= form_for :mobile_visit, :method =>  :patch,:url => "/mobile_visit/#{@visit.id}" do |f| %>
    <table cellpadding=10>
      <tr>
        <td>Visit Coordinator</td>
        <td>
          <select style='width: 100%' name='visit_coordinator' id='visitCoordinator' helptext='<%= t("forms.labels.select_visit_coordinator")%>' value="<%= @visit.coordinator %>">
            <% (@coordinators || []).each do |person| %>
                <option value="<%= person[0]%>"><%= person[1].titleize %></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td>
          Visit Date:
        </td>
        <td>
          <%= text_field_tag 'visit_date', @visit.visit_date.strftime("%d-%m-%Y"),
                             {:id => 'visit_date',
                              :field_type => 'date',
                              :helpText => t("menu.terms.visit_date"),
                              :maxDate => (Date.today + 20.year).to_date,
                              :minDate => Date.today.to_date,
                              :tt_pageStyleClass => "Date DatesOnly"} %>

        </td>
      </tr>
    </table>


    <%= submit_tag value="Submit"%>
<% end %>

app/views/mobile_visit/index.html.erb
<%= javascript_include_tag 'jquery.dataTables.min.js' %>

<style type="text/css">
  .even{
    background-color: #CCCCCC !important;
  }
  input,label{
    margin-top: 3px;
    font-size: 1.3em;

  }
  img{
    height: 30px;
    width: 25px;
  }
</style>
<script type="text/javascript">
  // Styling the table with datatables library
  $(document).ready(function() {
    // $.fn.dataTable.moment( 'MMM-YYYY' );
    $('#mobilevisits').DataTable({"bLengthChange": false,
      "bDestroy": true,
      "pageLength":5,
      "language": {
        "search": I18n.t('forms.labels.search'),
        "lengthMenu": "Display _MENU_ records per page",
        "zeroRecords": I18n.t('forms.labels.nothing_found'),
        "info": I18n.t('forms.labels.tbl_pages'),
        "infoEmpty": "No records available",
        "infoFiltered": I18n.t('forms.labels.filtered'),
        "oPaginate": {
          "sNext": I18n.t('forms.buttons.next'),
          "sPrevious": I18n.t('forms.buttons.previous')
        }
      }
    });
    search_box = $('#generalInventory').dataTable()
    search = document.getElementsByTagName("input")[0];
    search.setAttribute("id","search");
    document.getElementById('search').setAttribute("onclick","showKeyboard();");
    keyboard = document.getElementsByClassName("keypad")[0]
    showAlphaKeypad();
  } );


</script>

<div style="height: 8vh;border: 1px inset black; border-width: 0px 0px 3px 0px;">
  <h1 style="margin-left: 2vw;"><%= t('menu.terms.mobile_vist')%></h1>
</div>

<div style="height: 75vh; overflow: auto;">
  <table id="mobilevisits" class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead>
    <tr>
      <th style="border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;"><%= t('menu.terms.visit_coordinator')%></th>
      <th style="width: 15%;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;"><%= t('menu.terms.visit_date')%></th>
      <th style="width: 20%;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;"><%= t('menu.terms.number_of_items')%></th>
      <th style="width: 10%;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;"><%= t('menu.terms.actions')%></th>
    </tr>
    </thead>

    <tbody>
    <% (@visits || []).each do |visit| %>
        <tr>
          <td><%= visit.coordinator rescue "" %></td>
          <td><%= l(visit.visit_date, format: "%d %b, %Y") %></td>
          <td><%= visit.products %></td>
          <td>
            <div style="display: table-row; width: 100%;">
          <!--    <div style="display: table-cell;width: 50%;text-align: center;">
                  <img style="margin-left: 1vw;margin-right: 1vw" src="/assets/edit.png" title="Edit Visit"
                       onmousedown="window.location='/mobile_visit/<%= visit.id %>/edit'">
              </div>
           //-->
              <div style="display: table-cell;width: 50%;text-align: center;">
                  <img style="margin-left: 1vw;margin-right: 1vw" src="/assets/view.png" title="View Visit"
                       onmousedown="window.location='/mobile_visit/<%= visit.id %>'">
              </div>
              <% if visit.products.to_i == 0 %>
                <div style="display: table-cell;text-align: center;">
                  <img src="/assets/delete.png" title="Void Visit"
                       onmousedown="confirmAction('/void_mobile_visit/<%= visit.id %>', 'Are you Sure?')">
                </div>
              <% end %>
            </div>
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>
</div>

<div class="footer" >
  <button onmousedown="window.location = '/'" class="nav-bttn green" style="margin-right: 1vw;float: right;"><%= t("forms.buttons.finish")%></button>
  <button onmousedown="window.location = '/mobile_visit/new'" class="nav-bttn"
          style="margin-right: 1vw;float: right;" ><%= t("forms.buttons.create_visit")%></button>
</div>

<div id="keypad">
          <span class="keypad">
          </span>

</div>

app/views/mobile_visit/new.html.erb
<script>
  var tt_cancel_destination = "/mobile_visit";

  function set_ajaxURL_for_suggestions(url, filter_value) {
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url + filter_value + "&search_string=");
    listSuggestions(tstCurrentPage);
  }

</script>

<%= form_for :mobile_visit,  :url => mobile_visit_index_path do |f| %>

    <%= text_field_tag "visit_coordinator", params[:drug_name],
                       {:id => 'visit_coordinator',
                        :ajaxURL => '/user/users_names?filter_value=',
                        :field_type => 'alpha',
                        :helpText => t("forms.labels.select_visit_coordinator"),
                        :allowFreeText => false,
                        :tt_onLoad => "set_ajaxURL_for_suggestions('/user/users_names?filter_value=' ,'');" } %>

    <%= text_field_tag 'visit_date', Date.today.strftime("%d-%m-%Y"),
                       {:id => 'visit_date',
                        :field_type => 'date',
                        :helpText => t("menu.terms.visit_date"),
                        :maxDate => (Date.today + 20.year).to_date,
                        :minDate => Date.today.to_date,
                        :tt_pageStyleClass => "Date DatesOnly"} %>

    <%= submit_tag value="Submit"%>
<% end %>

app/views/mobile_visit/show.html.erb
<style type="text/css">
  .submitButton{
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    float: right;
    margin-right: 10px;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 1.2em;
  }
  img{
    height: 30px;
    width: 25px;
  }
  .even{
    background-color: #CCCCCC !important;
  }
</style>
<div id="dispenseForm" class="questionLayer" style="font-size: 0.9em;">
  <div style="margin-top: 10vh;margin-left: 20vw; height: 80vh;width: 45vw;background-color: #eeeeff;border: 3px outset black;">
    <div style="display: table;width: 100%;">
      <div style="display: table-row">
        <div style="display: table-cell;height: 45vh;">
          <%= form_for :mobile_visit_product, :url => mobile_visit_product_index_path  do |f| %>
              <div style="padding: 2%;" id="qtyDiv" >
                <div style="text-align: center;">
                  <label for="qty"><span style="font-weight: 200;font-size: 1.2em"><%= t('forms.labels.enter_amount_taken') %></span></label> <br/>
                  <input type="text" id="qty" style="font-size: 20px;" name="amount" required>
                </div>
                <div style="margin-top: 5px;text-align: center;">
                  <table width="98%" cellspacing="15" >
                    <tr>
                      <td class="customButton" onmousedown="append(1,'qty');"><span>1</span></td>
                      <td class="customButton" onmousedown="append(2,'qty');"><span>2</span></td>
                      <td class="customButton" onmousedown="append(3,'qty');"><span>3</span></td>
                    </tr>
                    <tr>
                      <td class="customButton" onmousedown="append(4,'qty');"><span>4</span></td>
                      <td class="customButton" onmousedown="append(5,'qty');"><span>5</span></td>
                      <td class="customButton" onmousedown="append(6,'qty');"><span>6</span></td>
                    </tr>
                    <tr>
                      <td class="customButton" onmousedown="append(7,'qty');"><span>7</span></td>
                      <td class="customButton" onmousedown="append(8,'qty');"><span>8</span></td>
                      <td class="customButton" onmousedown="append(9,'qty');"><span>9</span></td>
                    </tr>
                    <tr>
                      <td class="customButton" onmousedown="append(0,'qty');"><span>0</span></td>
                      <td class="customButton" onmousedown="append('.','qty');"><span>.</span></td>
                      <td class="customButton" onmousedown="append('del','qty');"><span>del</span></td>
                    </tr>
                  </table>
                  <table width="100" cellspacing="15" >
                    <tr>
                      <td>
                        <div class="submitButton" style="background-color: tomato !important;" onmousedown="cancelDispense()">
                          <%= t('forms.buttons.cancel')%>
                        </div>
                      </td>
                      <td colspan="2">
                        <%= submit_tag t('forms.buttons.finish'), :class => "submitButton"%>
                      </td>
                    </tr>
                  </table>
                </div>
              </div>
              <input type="hidden" value="<%= @visit.id%>" name="visit_id" />
              <input type="hidden" name="bottle_id" id="bottle_id"/>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="updateForm" class="questionLayer" style="font-size: 0.9em;">
  <div style="margin-top: 10vh;margin-left: 20vw; height: 80vh;width: 45vw;background-color: #eeeeff;border: 3px outset black;">
    <div style="display: table;width: 100%;">
      <div style="display: table-row">
        <div style="display: table-cell;height: 45vh;">
          <%= form_for :mobile_visit_product, :method => :patch,:url => "/mobile_visit_product/update" do |f| %>
              <div style="padding: 2%;" id="qtyDiv" >
                <div style="text-align: center;">
                  <label for="amount"><span style="font-weight: 200;font-size: 1.2em"><%= t('forms.labels.enter_amount_returned') %></span></label> <br/>
                  <input type="text" id="qtyRem" style="font-size: 20px;" name="amount" required>
                </div>
                <div style="margin-top: 5px;text-align: center;">
                  <table width="98%" cellspacing="15" >
                    <tr>
                      <td class="customButton" onmousedown="append(1,'qtyRem');"><span>1</span></td>
                      <td class="customButton" onmousedown="append(2,'qtyRem');"><span>2</span></td>
                      <td class="customButton" onmousedown="append(3,'qtyRem');"><span>3</span></td>
                    </tr>
                    <tr>
                      <td class="customButton" onmousedown="append(4,'qtyRem');"><span>4</span></td>
                      <td class="customButton" onmousedown="append(5,'qtyRem');"><span>5</span></td>
                      <td class="customButton" onmousedown="append(6,'qtyRem');"><span>6</span></td>
                    </tr>
                    <tr>
                      <td class="customButton" onmousedown="append(7,'qtyRem');"><span>7</span></td>
                      <td class="customButton" onmousedown="append(8,'qtyRem');"><span>8</span></td>
                      <td class="customButton" onmousedown="append(9,'qtyRem');"><span>9</span></td>
                    </tr>
                    <tr>
                      <td class="customButton" onmousedown="append(0,'qtyRem');"><span>0</span></td>
                      <td class="customButton" onmousedown="append('.','qtyRem');"><span>.</span></td>
                      <td class="customButton" onmousedown="append('del','qtyRem');"><span>del</span></td>
                    </tr>
                  </table>
                  <table width="100" cellspacing="15" >
                    <tr>
                      <td>
                        <div class="submitButton" style="background-color: tomato !important;" onmousedown="hideLayer('shadow', 'updateForm')">
                          <%= t('forms.buttons.cancel')%>
                        </div>
                      </td>
                      <td colspan="2">
                        <%= submit_tag t('forms.buttons.finish'), :class => "submitButton"%>
                      </td>
                    </tr>
                  </table>
                </div>
              </div>
              <input type="hidden" name="mvp_id" id="mvp_identifier"/>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div style="height: 12.5vh;padding: 10px;">
  <div style="display: table">
    <div style="display: table-row; width: 100%;">
      <div style="display: table-cell;width: 70vw;">
        <span style="font-weight: bold;font-size: 20px;"><%= t('menu.terms.mobile_vist') %></span><br/>
        <span style="font-weight: bold"><%= t('menu.terms.visit_date') %>: <%= l(@visit.visit_date, format: "%d %b %Y")%></span><br/>
        <span style="font-weight: bold"><%= t('menu.terms.visit_coordinator') %>: <%= @visit.coordinator.titleize %></span>
      </div>
      <div style="display: table-cell;">
          <div style="display: table-row">
            <div style="display: table-cell;vertical-align: top;">
              <img style="height: 30px;" src="/assets/barcode.jpg">
            </div>
            <div style="display: table-cell;">
              <input type="text" id="barcode" class="scanner"  autofocus>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

<div style="height:75vh; overflow: auto; width: 100%">
  <div style="display: table; width: 100%;">
    <div style="display: table-row">
      <div style="display: table-cell; padding: 10px;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;">
        <%= t('menu.terms.product') %>
      </div>
      <div style="display: table-cell; padding: 10px;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;">
        <%= t('menu.terms.bottle_id') %>
      </div>
      <div style="display: table-cell; padding: 10px;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;">
        <%= t('menu.terms.amount_taken') %>
      </div>
      <div style="display: table-cell; padding: 10px;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;">
        <%= t('menu.terms.amount_used') %>
      </div>
      <div style="display: table-cell; padding: 10px;border-right: 1px solid #ffffff; text-align: center;background-color: #006495; color: #FFFFFF;">
        <%= t('menu.terms.expiration_date') %>
      </div>
      <div style="display: table-cell; padding: 10px; text-align: center;background-color: #006495; color: #FFFFFF;">
        <%= t('menu.terms.actions') %>
      </div>
    </div>
    <% (@visit_products || []).each do |visit| %>
        <div style="display: table-row" class="<%= cycle("odd", "even")%>">
          <div style="display: table-cell; padding: 10px;">
            <%= visit["product"]%>
          </div>
          <div style="display: table-cell; padding: 10px; text-align: center;">
            <%= Misc.dash_formatter(visit["bottle_id"])%>
          </div>
          <div style="display: table-cell; padding: 10px;text-align: center;">
            <%= visit["amount_taken"]%>
          </div>
          <div style="display: table-cell; padding: 10px;text-align: center;">
            <%= visit["amount_used"]%>
          </div>
          <div style="display: table-cell; padding: 10px; text-align: center;">
            <%= l(visit["exp_date"], format: '%d %b %Y')%>
          </div>
          <div style="display: table-cell; text-align: center;vertical-align: middle;">
              <img style="float: left;" src="/assets/edit.png" title="Edit Item"
                   onmousedown="showLayer('shadow', 'updateForm'),document.getElementById('mvp_identifier').value = <%= visit["id"]%>">
            <% if  visit["voidable"]%>
            <img style="float: right;" src="/assets/delete.png" title="Void Item"
                 onmousedown="confirmAction('/void_mobile_visit_product/<%= visit["id"] %>', 'Are you Sure?')">
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

<div class="footer" >
  <div onmousedown="window.location = '/mobile_visit'" class="bttn bttn-success bttn-lg gradient" style="margin-right: 2vw;float: right;" type="button"><%= t('forms.buttons.finish') %></div>
</div>

<script type="text/javascript">
  var timerHand;

  function checkBarcode()
  {
    var barcodeTxt = document.getElementById("barcode");
    if (barcodeTxt.value.trim().match(/[A-Z0-9]+\$/)) {

      barcodeTxt.value = barcodeTxt.value.trim().replace(/\$/, "").replace(/\-/,"")
      if (barcodeTxt.value.toUpperCase().length >= 7)
      {
        showDispenseForm()
        document.getElementById("bottle_id").value= barcodeTxt.value.trim().toUpperCase();
      }
      else
      {
        barcodeTxt.value = "";
        initializeListener();
      }

    }
    else
    {
      initializeListener();
    }
  }

  function cancelDispense()
  {
    var barcodeTxt = document.getElementById("barcode");
    barcodeTxt.value = "";
    initializeListener();
    hideLayer('shadow', 'dispenseForm')
  }


  function initializeListener()
  {
    document.getElementById("barcode").focus();
    timerHand = setTimeout(function () {
      checkBarcode();
    }, 3000);

  }

  setTimeout(initializeListener(), 3000);

  function append(item,control){
    input = document.getElementById(control);
    if (item == "del"){
      input.value = qty.value.substring(0,input.value.toString().length-1)
    }
    else
    {
      input.value = input.value.toString() + item;
    }
  }

</script>