config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/index'

  get 'prescriptions/show'

  get 'prescriptions/create'

  get 'prescriptions/edit'

  root 'main#index'

  get "/main/settings"
  get "/select_report" => "main#select_report"
  post "/main/dispensation_report"
  post "/main/prescription_report"
  post "/main/stores_report"
  get "/time" => "main#time"

  get "/drug/search"
  get "/void_drug/:id" => "drug#destroy"
  post "/edit_drug" => "drug#edit"

  get "/void_general_inventory/:id" => "general_inventory#destroy"
  post "/void_general_inventory" => "general_inventory#destroy"
  post "/edit_general_inventory" => "general_inventory#edit"
  get "/general_inventory/expired_items"
  get "/general_inventory/expiring_items"
  get "/general_inventory/understocked"
  get "/general_inventory/wellstocked"
  get "view_gn_drug/:id" => "general_inventory#view_drug"
  get "/print_bottle_barcode/:id" => "general_inventory#print_bottle_barcode"
  get "/ajax_bottle/:id" => "general_inventory#ajax_bottle"
  get "/general_inventory/print_bottle_barcode"

  get "/username_availability" => "user#username_availability"

  get "/query_users" => "user#query"
  get "/void_user/:id" => "user#destroy"
  post "/edit_user" => "user#edit"
  get "/user/users_names"

  get "/void_prescriptions/:id" => "prescription#destroy"
  get "/prescriptions" => "prescription#ajax_prescriptions"
  post "/prescription/dispense"
  post "/prescription/edit"

  get "/print_dispensation_label/:id" => "dispensation#print_dispensation_label"
  get "/void_dispensation/:id" => "dispensation#destroy"
  

  get "/void_mobile_visit/:id" => "mobile_visit#destroy"

  get "/void_mobile_visit_product/:id" => "mobile_visit_product#destroy"

  resources :mobile_visit
  resources :mobile_visit_product
  resources :drug_threshold
  resources :prescriptions
  resources :drug
  resources :patient_identifiers

  resources :general_inventory do
    post 'pre_packing'
    collection do
      get 'print_pre_packed(/:id)', action: :print_pre_packed
      get 'list'
      post 'merge'
    end
  end

  resources :patients do
    collection do
      get 'given_names'
      get 'family_names'
    end
  end

  resources :user do
    collection do
      get 'roles'
    end
  end

  resources :dispensation do
    collection do
      post 'refill'
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
      get 'suggestions'
    end
  end

  resources :issues do
    collection do
      get 'select'
      post 'list'
    end
  end

  resources :sessions do
    collection do
      post 'login' , action: :create
      get 'logout' , action: :destroy
      get 'add_location'
      post 'workstation_location'
    end
  end
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  belongs_to :drug_category, :foreign_key =>  :drug_category_id
def ingredient
  temp = self.name.to_s.downcase

  if self.dose_form.present?
    temp = temp.gsub(self.dose_form.to_s.downcase, "")
  end

  if self.dose_strength.present?
    temp = temp.gsub(self.dose_strength.to_s.downcase, "")
  end

  temp.squish
end

  def category
    return self.drug_category.category
  end

end

app/controllers/drug_controller.rb
class DrugController < ApplicationController

  def search
    drugs = Drug.where("voided = ? and name like ? and drug_category_id = ? ", false, "%#{params[:search_string]}%",
               DrugCategory.find_by_category(params[:filter_value]).id) rescue []
    drug_names = drugs.map do |v|
      "<li value='#{v.name.html_safe}'>#{v.name.html_safe}</li>"
    end
    render html: drug_names.join('').html_safe and return
  end

  def index
    @drugs = Drug.where("voided = ?", false)
  end

  def destroy
    drug = Drug.where("drug_id = ?", params[:id]).first rescue nil
    if drug.blank?
      flash[:errors][:missing] = "Item was not found"
    else
      drug.voided =  true
      drug.save
      if drug.errors.blank?
        flash[:success] = "#{drug.name} was successfully deleted."
      else
        flash[:errors] = drug.errors.join(",")
      end
    end
    redirect_to "/drug" and return
  end

  def new
    render :layout => 'touch'
  end

  def create

    begin
      drug_name = ((params[:drug_ingredient].to_s rescue "") + " " + (params[:dose_strength].to_s rescue "") + " " + (params[:dose_form].to_s rescue "")).squish
      drug = Drug.where(name: drug_name).first_or_initialize
      drug.drug_category_id = DrugCategory.find_by_category(params[:drug_category]).id
      drug.name = drug_name
      drug.dose_strength = (params[:dose_strength].blank? ? nil : params[:dose_strength].squish)
      drug.dose_form = (params[:dose_form].blank? ? nil : params[:dose_form].squish)
      drug.save
    rescue ex
      flash[:errors] = ex.message
    end

    if drug.errors.blank?
      flash[:success] = "#{drug.name} was successfully created."
    else
      flash[:errors] = drug.errors.join(" , ")
    end

    redirect_to "/drug" and return
  end

  def edit
    if request.post?
      begin
        drug_name = ((params[:drug_ingredient].to_s rescue "") + " " + (params[:dose_strength].to_s rescue "") + " " + (params[:dose_form].to_s rescue "")).squish
        drug = Drug.find(params[:drug_id])
        drug.drug_category_id = DrugCategory.find_by_category(params[:drug_category]).id
        drug.name = drug_name
        drug.dose_strength = (params[:dose_strength].blank? ? nil : params[:dose_strength].squish)
        drug.dose_form = (params[:dose_form].blank? ? nil : params[:dose_form].squish)
        drug.save
      rescue => ex
        flash[:errors] = ex.message
      end


      if drug.errors.blank?
        flash[:success] = "#{drug.name} was successfully edited."
      else
        flash[:errors] = drug.errors.join(" , ")
      end

      redirect_to "/drug" and return
    else
      @drug = Drug.find(params[:id])
      render :layout => 'touch'
    end

  end
end

app/helpers/drug_helper.rb
module DrugHelper
end

app/views/drug/edit.html.erb
<script>
  var tt_cancel_destination = "/drug";

  function set_ajaxURL_for_suggestions(url, filter_value) {
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url + filter_value + "&search_string=");
    listSuggestions(tstCurrentPage);
  }
</script>


<%= form_for :drug,  :url => edit_drug_path do |f| %>
    <table cellpadding=10>
      <tr>
        <td>
          <%= text_field_tag "drug_ingredient", @drug.ingredient,
                             {:id => 'drug_ingredient',
                              :field_type => 'alpha',
                              :helpText => t('forms.labels.enter_ingredient'),
                              :allowFreeText => false} %>
        </td>
      </tr>
      <tr>
        <td>Dose Strength</td>
        <td>
          <%= text_field_tag "dose_strength", @drug.dose_strength,
                             {:id => 'dose_strength',
                              :field_type => 'password',
                              :helpText => t('forms.labels.enter_dose_strength'),
                              :allowFreeText => false} %>
        </td>
      </tr>
      <tr>
        <td>Dose Form</td>
        <td>
          <select style='width: 100%' name='dose_form' id='dose_form' value="<%= @drug.dose_form.titleize %>" helptext="'<%= t('forms.labels.enter_dose_form')%>'"
                  doublepane="false">
            <% (dose_forms || []).each do |option| %>
                <option value="<%= option%>"><%= option.titleize %></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td>Drug Category</td>
        <td>
          <select style='width: 100%' name='drug_category' id='drug_category' helptext='Drug Category'
                  doublepane="false">
            <% (drug_categories || []).each do |option| %>
                <option value="<%= option%>"><%= option.titleize %></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <input type="hidden" value="<%= @drug.id%>" id="drug_id" name="drug_id" />
      </tr>
    </table>


    <%= submit_tag value="Submit"%>
<% end %>


<script>

  if(document.getElementById("date")) {

    document.getElementById("date").setAttribute("maxdate", (new Date((new Date()).setDate((new Date()).getDate() + 1000))));

    document.getElementById("date").setAttribute("mindate", (new Date((new Date()).setDate((new Date()).getDate() - 1))));

  }

</script>

app/views/drug/index.html.erb
<%= javascript_include_tag 'jquery.dataTables.min.js' %>
<style type="text/css">
  .even{
    background-color: #CCCCCC !important;
  }
  input,label{
    margin-top: 3px;
    font-size: 1.7em;
  }
  th,td{
    font-size: 1.7em;
  }
</style>
<script type="text/javascript">
  // Styling the table with datatables library
  $(document).ready(function() {
    // $.fn.dataTable.moment( 'MMM-YYYY' );
    $('#generalInventory').DataTable({"bLengthChange": false,
      "bDestroy": true,
      "pageLength":7,
      "language": {
        "search": I18n.t('forms.labels.search'),
        "lengthMenu": "Display _MENU_ records per page",
        "zeroRecords": I18n.t('forms.labels.nothing_found'),
        "info": I18n.t('forms.labels.tbl_pages'),
        "infoEmpty": "No records available",
        "infoFiltered": I18n.t('forms.labels.filtered'),
        "oPaginate": {
          "sNext": I18n.t('forms.buttons.next'),
          "sPrevious": I18n.t('forms.buttons.previous')
        }
      }
    });
    search_box = $('#generalInventory').dataTable()
    search = document.getElementsByTagName("input")[0];
    search.setAttribute("id","search");
    document.getElementById('search').setAttribute("onclick","showKeyboard();");
    keyboard = document.getElementsByClassName("keypad")[0]
    showAlphaKeypad();
  } );
</script>
<div style="height: 8vh;border: 1px inset black; border-width: 0px 0px 3px 0px;">
  <h1 style="margin-left: 2vw;"><%= t('menu.terms.drug_list')%></h1>
</div>

<div style="height: 75vh; overflow: auto;">
  <table id="generalInventory" class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead>
    <tr>
      <th ><%= t('menu.terms.drug_name')%></th>
      <th style="width: 20%;"><%= t('menu.terms.dose_form')%></th>
      <th style="width: 20%;"><%= t('forms.labels.drug_category')%></th>
      <th style="width: 15%;"><%= t('menu.terms.actions')%></th>
    </tr>
    </thead>

    <tbody>
    <% (@drugs || []).each do |drug| %>
        <tr>
          <td><%= drug.name.titleize rescue "" %></td>
          <td><%= drug.dose_form %></td>
          <td><%= drug.category %></td>
          <td>

            <img style="float: left;" src="/assets/edit.png" onmousedown="window.location='/drug/<%= drug.id %>/edit'" title="Edit Drug">
            <img style="float: right;" src="/assets/delete.png" title="Void Drug"
                 onmousedown="confirmAction('/void_drug/<%= drug.id %>', 'Are you Sure?')">
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>
</div>

<div class="footer" >
  <button class="nav-bttn green" style="float: right;margin-right: 1vw;" onmousedown="window.location='/main/settings'">
    <%= t('forms.buttons.finish')%>
  </button>
  <button class="nav-bttn" style="float: right;margin-right: 1vw;" onmousedown="window.location='/drug/new'">
    <%= t('forms.buttons.add_drug') %>
  </button>
</div>

<div id="keypad">
          <span class="keypad">
          </span>

</div>

app/views/drug/new.html.erb
<script>
  var tt_cancel_destination = "/";
  tstCurrentDate = <%= Date.today.strftime("%d-%m-%Y") %>;

  function set_ajaxURL_for_suggestions(url, filter_value) {
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url + filter_value + "&search_string=");
    listSuggestions(tstCurrentPage);
  }
</script>


<%= form_for :drug,  :url =>  drug_index_path   do |f| %>

          <%= text_field_tag "drug_ingredient", params[:drug_name],
                             {:id => 'drug_ingredient',
                              :field_type => 'alpha',
                              :helpText => t('forms.labels.enter_ingredient'),
                              :allowFreeText => false} %>

          <%= text_field_tag "dose_strength", params[:dose_strength],
                             {:id => 'dose_strength',
                              :field_type => 'password',
                              :helpText => t('forms.labels.enter_dose_strength'),
                              :allowFreeText => false} %>

          <select style='width: 100%' name='dose_form' id='dose_form' helptext='<%= t('forms.labels.enter_dose_form')%>'
                  doublepane="false">
            <% (dose_forms || []).each do |option| %>
                <option value="<%= option%>"><%= option.titleize %></option>
            <% end %>
          </select>

          <select style='width: 100%' name='drug_category' id='drug_category' helptext='<%= t('forms.labels.drug_category')%>'
                  doublepane="false">
            <% (drug_categories || []).each do |option| %>
                <option value="<%= option%>"><%= option.titleize %></option>
            <% end %>
          </select>
    </table>


    <%= submit_tag value="Submit"%>
<% end %>


<script>

  if(document.getElementById("date")) {

    document.getElementById("date").setAttribute("maxdate", (new Date((new Date()).setDate((new Date()).getDate() + 1000))));

    document.getElementById("date").setAttribute("mindate", (new Date((new Date()).setDate((new Date()).getDate() - 1))));

  }

</script>