config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/index'

  get 'prescriptions/show'

  get 'prescriptions/create'

  get 'prescriptions/edit'

  root 'main#index'

  get "/main/settings"
  get "/select_report" => "main#select_report"
  post "/main/dispensation_report"
  post "/main/prescription_report"
  post "/main/stores_report"
  get "/time" => "main#time"

  get "/drug/search"
  get "/void_drug/:id" => "drug#destroy"
  post "/edit_drug" => "drug#edit"

  get "/void_general_inventory/:id" => "general_inventory#destroy"
  post "/void_general_inventory" => "general_inventory#destroy"
  post "/edit_general_inventory" => "general_inventory#edit"
  get "/general_inventory/expired_items"
  get "/general_inventory/expiring_items"
  get "/general_inventory/understocked"
  get "/general_inventory/wellstocked"
  get "view_gn_drug/:id" => "general_inventory#view_drug"
  get "/print_bottle_barcode/:id" => "general_inventory#print_bottle_barcode"
  get "/ajax_bottle/:id" => "general_inventory#ajax_bottle"
  get "/general_inventory/print_bottle_barcode"

  get "/username_availability" => "user#username_availability"

  get "/query_users" => "user#query"
  get "/void_user/:id" => "user#destroy"
  post "/edit_user" => "user#edit"
  get "/user/users_names"

  get "/void_prescriptions/:id" => "prescription#destroy"
  get "/prescriptions" => "prescription#ajax_prescriptions"
  post "/prescription/dispense"
  post "/prescription/edit"

  get "/print_dispensation_label/:id" => "dispensation#print_dispensation_label"
  get "/void_dispensation/:id" => "dispensation#destroy"
  

  get "/void_mobile_visit/:id" => "mobile_visit#destroy"

  get "/void_mobile_visit_product/:id" => "mobile_visit_product#destroy"

  resources :mobile_visit
  resources :mobile_visit_product
  resources :drug_threshold
  resources :prescriptions
  resources :drug
  resources :patient_identifiers

  resources :general_inventory do
    post 'pre_packing'
    collection do
      get 'print_pre_packed(/:id)', action: :print_pre_packed
      get 'list'
      post 'merge'
    end
  end

  resources :patients do
    collection do
      get 'given_names'
      get 'family_names'
    end
  end

  resources :user do
    collection do
      get 'roles'
    end
  end

  resources :dispensation do
    collection do
      post 'refill'
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
      get 'suggestions'
    end
  end

  resources :issues do
    collection do
      get 'select'
      post 'list'
    end
  end

  resources :sessions do
    collection do
      post 'login' , action: :create
      get 'logout' , action: :destroy
      get 'add_location'
      post 'workstation_location'
    end
  end
end

app/models/user.rb
require 'digest/sha1'
require 'digest/sha2'

class User < ActiveRecord::Base

  #establish_connection :billing_import
  self.table_name = "users"
  self.primary_key = "user_id"

  #include Openmrs

  validates :username, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :password, presence: true, length: { minimum: 6 }

  #before_create :before_create
  before_save :encrypt_password

  cattr_accessor :current

  belongs_to :person, -> {where voided: false}, :foreign_key => :person_id
  has_many :user_properties, :foreign_key => :user_id
  has_many :user_roles, :foreign_key => :user_id
  has_many :names,-> { where "voided =  false"}, :class_name => 'PersonName', :foreign_key => :person_id

  def self.get_similar_user(username)
    users = User.where("username LIKE ?", "%#{username}%")
    return users
  end

  def first_name
    self.person.names.last.given_name rescue ''
  end

  def last_name
    self.person.names.last.family_name rescue ''
  end

  def display_name
    name = self.person.names.last

    return "#{name.given_name} #{name.family_name}".titleize
  end

  def fullname
    display_name
  end

  def language

  end

  def self.random_string(len)
    #generate a random password consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
    return newpass
  end

  def encrypt_password
    if salt.blank?
      self.salt = User.random_string(10)
      self.password = encrypt(self.password, self.salt)
    end
  end

  def encrypt(password,salt)
    Digest::SHA1.hexdigest(password+salt)
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if !user.blank?
      user.valid_password?(password) ? user : nil
    end
  end
  def password
    # We expect that the default OpenMRS interface is used to create users
    #self.password = encrypt(self.plain_password, self.salt) if self.plain_password

    self[:password]
  end

  def password_digest(pwd)
    encrypt(pwd, salt)
  end

  def encrypted_password
    self.password
  end


  def valid_password?(password)
    return false if encrypted_password.blank?
    is_valid = Digest::SHA1.hexdigest("#{password}#{salt}") == encrypted_password	|| encrypt(password, salt) == encrypted_password || Digest::SHA512.hexdigest("#{password}#{salt}") == encrypted_password
  end

  def role
    self.user_roles.last.role rescue ''
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.where("retired = ?", false)
  end

  def new
    @user = User.new
    @targeturl = "/user"
    render :layout => "touch"
  end

  def create

    existing_user = User.where(username: params[:user][:username]) rescue nil

    if !existing_user.blank?
      flash[:notice] = 'Username already in use'
      redirect_to "/user/new" and return
    end
    if (params[:password] != params[:confirm_password])
      flash[:notice] = 'Password Mismatch'
      redirect_to :action => 'new' and return
    end

    person = Person.create()
    person.names.create(given_name: params[:user][:given_name], family_name: params[:user][:family_name])

    @user = User.create(username: params[:user][:username], password: params[:password],
                        creator: params[:creator], person_id: person.id)

    @user.user_roles.create(role: Role.find_by_role( params[:user_role][:role_id]).role)

    if @user.errors.blank?
      flash[:notice] = 'User was successfully created.'
    else
      flash[:notice] = 'Oops! User was not created!.'
      redirect_to "/user/new" and return
    end
    redirect_to "/user"

  end

  def show
    @user = User.find(params[:id])
    @targeturl = "/users"
    render :layout => "menu"
  end

  def edit
    @user = User.find(params[:id])
    @section = (params[:section] || 'General')
    render :layout =>  "touch"
  end

  def update

    user = User.find(params[:id])
    case params[:section]
      when "General"
        User.transaction do
          person = user.person
          person.names.create(given_name: params[:user][:given_name], family_name: params[:user][:family_name])
          user.user_roles.destroy_all
          user.user_roles.create(role: Role.find_by_role( params[:user_role][:role_id]).role)
        end

        if user.errors.blank?
          flash[:success] = "User language preference successfully updated"
        else
          raise user.errors.inspect
          flash[:errors] = "Failed to update user details"
        end
      when "password"
        user.update_attributes(password: params[:password], salt: nil)
        if user.errors.blank?
          flash[:success] = "User password successfully updated"
        else
          flash[:errors] = t("messages.invalid_credentials")
        end
    end
    redirect_to "/main/settings" and return

  end
  def destroy
    user = User.find(params[:id])
    user.update_attributes(retired: true)
    redirect_to "/user" and return
  end


  def logout

  end

  def username_availability
    user = User.find_by_username(params[:search_str])
    render :text => user.blank? ? '' : 'N/A' and return
  end

  def query
    results = []

    users = User.page((params[:page].to_i rescue 1)).per((params[:size].to_i rescue 20)).each

    users.each do |user|

      record = {
          "username" => "#{user.username}",
          "name" => "#{user.fullname}",
          "roles" => "#{user.role}",
          "active" => (user.active rescue false),
          "id" => user.id
      }

      results << record

    end

    render :text => results.to_json

  end

  def users_names
    coordinators = User.where("retired = ? AND role in (?)", false, ["administrator","Pharmacist"]) rescue []
    names = coordinators.map do |v|
      "<li value='#{v.user_id}'>#{v.fullname.html_safe}</li>"
    end
    render :text => names.join('') and return
  end

  def roles
    role_conditions = ["role LIKE (?)", "%#{params[:value]}%"]
    roles = Role.where( role_conditions)
    roles = roles.map do |r|
      "<li value='#{r.role}'>#{r.role.gsub('_',' ').capitalize}</li>"
    end
    render :text => roles.join('') and return
  end

  private

  def user_params
    params.require(:user).permit(:username,:password,:creator,:voided)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<script type="text/javascript" defer>

    tt_cancel_destination = '/main/settings';
</script>

<%= form_for :user,method: 'PATCH',  url: user_path do |f| %>

    <% if @section == 'General' %>
    <p><label for="user_given_name">First name</label><br/>
      <%= text_field 'user', 'given_name', :ajaxURL=> '/patients/given_names?search_string=',
                     :value => @user.first_name ,:allowFreeText => true%></p>

    <p><label for="user_family_name">Last name</label><br/>
      <%= text_field 'user', 'family_name', :ajaxURL => '/patients/family_names?search_string=',
                     :value => (@user.last_name || nil), :allowFreeText => true%></p>
    <br>
    <p><label for="user_role_role_id">User Role</label></br>
      <%= text_field 'user_role', 'role_id', :xhelpText => 'User role',
                     :ajaxURL => '/user/roles?field=role&value='%></p>
    <br>
   <% else %>
      <%= f.label :password %>
      <br>
      <%= password_field_tag(:password, nil, :helpText => 'Enter password',
                             :textCase => "lower", :field_type => "password",
                             :validationRule =>"\\w{6}\\w*",
                             :validationMessage =>"Password less than SIX characters.",:minlength => 6 ,
                             :tt_onLoad => "inform(); barcodeId = 'touchscreenInput1';") %><br>

      <%= password_field_tag(:confirm_password, nil, :helpText => 'Confirm password',
                             :validationRule =>"\\w{6}\\w*",
                             :validationMessage =>"Password less than SIX characters.",:minlength => 6 ,
                             :textCase => "lower", :field_type => "password") %><br>

    <% end %>
    <%= hidden_field_tag 'section', @section %>
<% end %>

app/views/user/index.html.erb
<%= javascript_include_tag 'jquery.dataTables.min.js' %>
<style type="text/css">
  .even{
    background-color: #CCCCCC !important;
  }
  input,label{
    margin-top: 3px;
    font-size: 1.7em;
  }
  th,td{
    font-size: 1.7em;
  }
</style>
<script type="text/javascript">
  // Styling the table with datatables library
  $(document).ready(function() {
    // $.fn.dataTable.moment( 'MMM-YYYY' );
    $('#generalInventory').DataTable({
      "bLengthChange": false,
      "bDestroy": true,
      "pageLength":5,
      "language": {
        "search": I18n.t('forms.labels.search'),
        "lengthMenu": "Display _MENU_ records per page",
        "zeroRecords": I18n.t('forms.labels.nothing_found'),
        "info": I18n.t('forms.labels.tbl_pages'),
        "infoEmpty": "No records available",
        "infoFiltered": I18n.t('forms.labels.filtered'),
        "oPaginate": {
          "sNext": I18n.t('forms.buttons.next'),
          "sPrevious": I18n.t('forms.buttons.previous')
        }
      }
    });
    search_box = $('#generalInventory').dataTable()
    search = document.getElementsByTagName("input")[0];
    search.setAttribute("id","search");
    document.getElementById('search').setAttribute("onclick","showKeyboard();");
    keyboard = document.getElementsByClassName("keypad")[0]
    showAlphaKeypad();
  } );
</script>
<div style="height: 8vh;border: 1px inset black; border-width: 0px 0px 3px 0px;">
  <h1 style="margin-left: 2vw;">Registered Users</h1>
</div>

<div style="height: 75vh; overflow: auto;">
  <table id="generalInventory" class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead>
    <tr>
      <th><%= t('menu.terms.users_name')%></th>
      <th style="width: 15%;"><%= t('forms.labels.username')%></th>
      <th style="width: 25%;"><%= t('menu.terms.role')%></th>
      <th style="width: 15%;"><%= t('menu.terms.actions')%></th>
    </tr>
    </thead>

    <tbody>
    <% (@users || []).each do |user| %>
        <tr>
          <td><%= user.display_name %></td>
          <td><%= user.username %></td>
          <td><%= user.role.titleize %></td>
          <td>

            <img style="float: left;" src="/assets/edit.png" onmousedown="window.location='/user/<%= user.id %>/edit'" title="Edit User">
            <img style="float: right;" src="/assets/delete.png" title="Void Item"
                 onmousedown="confirmAction('/void_user/<%= user.id %>', 'Are you Sure?')">
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>
</div>

<div class="footer" >
  <button onmousedown="window.location = '/main/settings'" class="nav-bttn green" style="margin-right: 1vw;float: right;">
    <%= t('forms.buttons.finish')%></button>
  <button onmousedown="window.location = '/user/new'" class="nav-bttn " style="margin-right: 1evw;float: right;">
    <%= t('forms.buttons.add_user')%></button>
</div>
<div id="keypad">
          <span class="keypad">
          </span>

</div>

app/views/user/new.html.erb
<script type="text/javascript" defer>

    tt_cancel_destination = '/users';
    tt_cancel_show = '/';

</script>

<%= form_for :user,  url: user_index_path do |f| %>

        <p><label for="user_given_name">First name</label><br/>
          <%= text_field 'user', 'given_name', :ajaxURL=> '/patients/given_names?search_string=', :value => nil ,:allowFreeText => true%></p>

        <p><label for="user_family_name">Last name</label><br/>
          <%= text_field 'user', 'family_name', :ajaxURL => '/patients/family_names?search_string=', :value => nil, :allowFreeText => true%></p>

        <%= f.label :username %>
        <br>
        <%= f.text_field :username, :class => "input_cell", :placeholder => "Username", :required => true,
                         :textCase => "lower", :uniq_check => "/username_availability?search_str=" %>
        <%= f.label :password %>
        <br>
        <%= password_field_tag(:password, nil, :helpText => 'Enter password',
                               :textCase => "lower", :field_type => "password",
                               :validationRule =>"\\w{6}\\w*", :validationMessage =>"Password less than SIX characters.",:minlength => 6 ,
                               :tt_onLoad => "inform(); barcodeId = 'touchscreenInput1';") %><br>

        <%= password_field_tag(:confirm_password, nil, :helpText => 'Confirm password',
                               :validationRule =>"\\w{6}\\w*", :validationMessage =>"Password less than SIX characters.",:minlength => 6 ,
                               :textCase => "lower", :field_type => "password") %><br>

        <br>
        <p><label for="user_role_role_id">User Role</label></br>
        <%= text_field 'user_role', 'role_id', :xhelpText => 'User role', :ajaxURL => '/user/roles?field=role&value='%></p>

        <%= hidden_field_tag 'creator', User.current.id %>

<% end %>