config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/index'

  get 'prescriptions/show'

  get 'prescriptions/create'

  get 'prescriptions/edit'

  root 'main#index'

  get "/main/settings"
  get "/select_report" => "main#select_report"
  post "/main/dispensation_report"
  post "/main/prescription_report"
  post "/main/stores_report"
  get "/time" => "main#time"

  get "/drug/search"
  get "/void_drug/:id" => "drug#destroy"
  post "/edit_drug" => "drug#edit"

  get "/void_general_inventory/:id" => "general_inventory#destroy"
  post "/void_general_inventory" => "general_inventory#destroy"
  post "/edit_general_inventory" => "general_inventory#edit"
  get "/general_inventory/expired_items"
  get "/general_inventory/expiring_items"
  get "/general_inventory/understocked"
  get "/general_inventory/wellstocked"
  get "view_gn_drug/:id" => "general_inventory#view_drug"
  get "/print_bottle_barcode/:id" => "general_inventory#print_bottle_barcode"
  get "/ajax_bottle/:id" => "general_inventory#ajax_bottle"
  get "/general_inventory/print_bottle_barcode"

  get "/username_availability" => "user#username_availability"

  get "/query_users" => "user#query"
  get "/void_user/:id" => "user#destroy"
  post "/edit_user" => "user#edit"
  get "/user/users_names"

  get "/void_prescriptions/:id" => "prescription#destroy"
  get "/prescriptions" => "prescription#ajax_prescriptions"
  post "/prescription/dispense"
  post "/prescription/edit"

  get "/print_dispensation_label/:id" => "dispensation#print_dispensation_label"
  get "/void_dispensation/:id" => "dispensation#destroy"
  

  get "/void_mobile_visit/:id" => "mobile_visit#destroy"

  get "/void_mobile_visit_product/:id" => "mobile_visit_product#destroy"

  resources :mobile_visit
  resources :mobile_visit_product
  resources :drug_threshold
  resources :prescriptions
  resources :drug
  resources :patient_identifiers

  resources :general_inventory do
    post 'pre_packing'
    collection do
      get 'print_pre_packed(/:id)', action: :print_pre_packed
      get 'list'
      post 'merge'
    end
  end

  resources :patients do
    collection do
      get 'given_names'
      get 'family_names'
    end
  end

  resources :user do
    collection do
      get 'roles'
    end
  end

  resources :dispensation do
    collection do
      post 'refill'
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
      get 'suggestions'
    end
  end

  resources :issues do
    collection do
      get 'select'
      post 'list'
    end
  end

  resources :sessions do
    collection do
      post 'login' , action: :create
      get 'logout' , action: :destroy
      get 'add_location'
      post 'workstation_location'
    end
  end
end

app/models/general_inventory.rb
class GeneralInventory < ActiveRecord::Base
  belongs_to :drug, :foreign_key => :drug_id
  before_create :complete_record

  validates :expiration_date, :presence => true
  validates :date_received, :presence => true
  validates :received_quantity, :presence => true
  validates :current_quantity, :presence => true
  validates :received_quantity, :numericality => { :only_integer => true }
  validates :received_quantity, :numericality => { :greater_than => -1 }
  validates :current_quantity, :numericality => { :only_integer => true }
  validates :current_quantity, :numericality => { :greater_than => -1 }
  validates_associated :drug

  include Misc

  def drug_name
    #this method handles the need to access the drug name associated to the inventory entry
    self.drug.name.humanize.gsub(/\b('?[a-z])/) { $1.capitalize } rescue ""
  end

  def drug_category
    self.drug.category.humanize.gsub(/\b('?[a-z])/) { $1.capitalize } rescue ""
  end

  def bottle_id
    return self.gn_identifier
  end

  def self.void_item(bottle_id)
    item = GeneralInventory.find(bottle_id)
    unless item.blank?
      item.voided = true
      item.void_reason = "Unspecified"
      item.save
      return item
    end

    return false
  end

  def dose_form
    self.drug.dose_form
  end
  private

  def complete_record
    self.current_quantity = self.received_quantity
    self.date_received = Date.current
    self.created_by = User.current.id
    unless !self.gn_identifier.blank?
      last_id = GeneralInventory.order(gn_inventory_id: :desc).first.id rescue "0"
      next_number = (last_id.to_i+1).to_s.rjust(6,"0")
      check_digit = calculate_check_digit(next_number)
      self.gn_identifier = "G#{next_number}#{check_digit}"
    end
  end
end

app/controllers/general_inventory_controller.rb
class GeneralInventoryController < ApplicationController

  def index
    location_id = session[:location]

    @inventory = GeneralInventory
                  .where(voided: false, location_id: location_id)
                  .joins(:drug => :drug_category)       # eager load
                  .select('general_inventories.*, drugs.name AS drug_name, drug_categories.category AS drug_category_name')
                  .group('general_inventories.drug_id')
                  .having('SUM(general_inventories.current_quantity) > 0')
  end

  def new
    render :layout => "touch"
  end

  def edit
    if request.post?
      # Edit a new record for general inventory
      @new_stock_entry = GeneralInventory.find_by_gn_identifier(params[:bottle_id])

      if @new_stock_entry.blank?
        flash[:errors] = "Item could not be found"
      else
        @new_stock_entry.expiration_date = params[:expiry_date].to_date rescue nil
        @new_stock_entry.received_quantity = params[:amount_received].to_i + (@new_stock_entry.received_quantity - @new_stock_entry.current_quantity)
        @new_stock_entry.current_quantity = params[:amount_received].to_i
        @new_stock_entry.location_id = session[:location]

        GeneralInventory.transaction do
          @new_stock_entry.save
        end

        if @new_stock_entry.errors.blank?
          flash[:success] = "#{@new_stock_entry.drug_name} (Bottle #: #{@new_stock_entry.gn_identifier}) was successfully updated."
        else
          flash[:errors] = @new_stock_entry.errors
        end
      end

      redirect_to "/" and return

    else
      @item = GeneralInventory.find(params[:id])
      render :layout => "touch"
    end
  end

  def create

    # Create a new record for general inventory
    #raise params.inspect
    count = params['number_of_items'].to_i rescue 0
    drug_id = Drug.find_by_name(params[:drug_name]).id rescue nil

    if drug_id.blank?
      flash[:errors] = "Item #{params[:drug_name]} was not found"
      redirect_to "/" and return
    else
      ids = []

      GeneralInventory.transaction do
        (0..count).each do |i|
          @new_stock_entry = GeneralInventory.new
          @new_stock_entry.drug_id = drug_id
          @new_stock_entry.current_quantity = params[:amount_received]
          @new_stock_entry.expiration_date = params[:expiry_date].to_date rescue nil
          @new_stock_entry.received_quantity = params[:amount_received]
          @new_stock_entry.date_received = Date.current
          @new_stock_entry.location_id = session[:location]
          @new_stock_entry.save

          if @new_stock_entry.errors.blank?
            ids << @new_stock_entry.id
          else
            flash[:errors] = @new_stock_entry.errors.join(",")
            redirect_to "/" and return
          end
        end
      end

      if ids.length > 1
        flash[:success] = "#{ids.length} #{t('messages.items_of')} #{params[:drug_name]} #{t('messages.add_items_success')}."
        print_and_redirect("/general_inventory/print_bottle_barcode?ids=#{ids.join(',')}", "/")
      else
        flash[:success] = "#{params[:drug_name]} #{t('messages.add_item_success')}."
        print_and_redirect("/print_bottle_barcode/#{ids.first}", "/")
      end
    end

  end

  def destroy
    #Delete an item from general inventory

    item = GeneralInventory.void_item(params[:id])
    if item.blank?
      flash[:errors]= "Item with bottle id #{params[:general_inventory][:gn_id]} could not be found"
    elsif item.errors.blank?
      flash[:success] = "#{item.drug_name} #{item.gn_identifier} was successfully deleted."
=begin
      news = News.where("refers_to = ? AND resolved = ?",
                        params[:general_inventory][:gn_id], false).first
      unless news.blank?
        news.resolved = true
        news.resolution = "Item was voided"
        news.date_resolved= Date.today
        news.save
      end
=end
    else
      flash[:errors] = item.errors
    end

    redirect_to "/general_inventory"
  end

  def print_bottle_barcode
    #This function prints bottle barcode labels for both inventory types
    id = params[:ids].split(',') rescue params[:id]
    entry = GeneralInventory.find(id)
#    raise params[:id].inspect
    if entry.is_a?(Array)
      print_string = ""
      (entry || []).each do |bottle|
        print_string += "#{Misc.create_bottle_label(bottle.drug_name,bottle.gn_identifier,bottle.expiration_date)}\n"
      end
    else
      print_string = Misc.create_bottle_label(entry.drug_name,entry.gn_identifier,entry.expiration_date)
    end

    chars = ("a".."z").to_a  + ("0".."9").to_a
    rand_str = ""
    1.upto(7) { |i| rand_str << chars[rand(chars.size-1)] }
    send_data(print_string,:type=>"application/label; charset=utf-8", :stream=> false, :filename=>"#{rand_str}.lbl", :disposition => "inline")
  end
   
  def ajax_bottle
    entry = GeneralInventory
              .includes(:drug)
              .find_by(gn_identifier: params[:id], location_id: session[:location], voided: false)

    if entry.blank?
      render plain: 'false'
    else
      render json: {
        name: entry.drug.name,
        currentQty: entry.current_quantity
      }
    end
  end

  def show
    # Fetch the inventory item for the current location
    @item = GeneralInventory.find_by(
      gn_identifier: params[:id].to_s,
      location_id: session[:location]
    )

    if @item.blank?
      flash[:errors] = "Item with ID #{params[:id]} not found in this location"
      redirect_to "/" and return
    end

    # Load all transaction records for this inventory item at this location
    @records = Issue.where(inventory_id: @item.gn_inventory_id).order(issue_date: :desc)

    # Show the total issued quantity across all locations
    # total_issued = Issue.where(inventory_id: GeneralInventory.where(gn_identifier: @item.gn_identifier).pluck(:gn_inventory_id)).sum(:quantity)
  end

  def list
    @drug = Drug.find_by_drug_id(params[:drug_id])
    @inventory = GeneralInventory.where("current_quantity > ? and drug_id = ? and location_id = ? and voided = ?",
                                        0, params[:drug_id] ,session[:location], false)
  end

  def pre_packing
    GeneralInventory.transaction do
      @item = GeneralInventory.where("gn_identifier = ? ", params[:bottle_id]).lock(true).first
      @item.current_quantity = @item.current_quantity.to_i - params[:pre_pack_amount].to_i
      @item.received_quantity = @item.received_quantity.to_i - params[:pre_pack_amount].to_i
      @item.save

      if @item.errors.blank?
        @new_stock_entry = GeneralInventory.new
        @new_stock_entry.drug_id = @item.drug_id
        @new_stock_entry.current_quantity = params[:pre_pack_amount]
        @new_stock_entry.expiration_date = @item.expiration_date
        @new_stock_entry.received_quantity = params[:pre_pack_amount]
        @new_stock_entry.date_received = Date.current
        @new_stock_entry.location_id = @item.location_id
        @new_stock_entry.save

        if @new_stock_entry.errors.blank?
          flash[:success] = "#{params[:bottle_id]} was successfully issued."
          print_and_redirect("/general_inventory/print_pre_packed/#{@new_stock_entry.id}", "/general_inventory/#{@item.gn_identifier}")
        else
          flash[:errors] = "Insufficient stock on hand"
          redirect_to "/general_inventory/#{@item.gn_identifier}" and return
        end
      end
    end
  end

  def merge
    bottles = GeneralInventory.where(gn_inventory_id: params[:bottle_ids].split(','))
    quantity = 0
    GeneralInventory.transaction do
      (bottles || []).each do |bottle|
        quantity += bottle.current_quantity.to_i
        bottle.received_quantity = bottle.received_quantity.to_i - bottle.current_quantity.to_i
        bottle.current_quantity = 0
        bottle.save
      end

      item = bottles.first

      @new_stock_entry = GeneralInventory.new
      @new_stock_entry.drug_id = item.drug_id
      @new_stock_entry.current_quantity = quantity
      @new_stock_entry.expiration_date = item.expiration_date
      @new_stock_entry.received_quantity = quantity
      @new_stock_entry.date_received = Date.current
      @new_stock_entry.location_id = item.location_id
      @new_stock_entry.save

      if @new_stock_entry.errors.blank?
        flash[:success] = "Items were successfully merged."
        print_and_redirect("/print_bottle_barcode/#{@new_stock_entry.id}", "/general_inventory/list?drug_id=#{item.drug_id}")
      else
        flash[:errors] = "Items could not be merged"
        redirect_to "/general_inventory/#{@new_stock_entry.gn_identifier}" and return
      end
    end
  end

  def print_pre_packed
    #This function prints bottle barcode labels for both inventory types
    id = params[:ids].split(',') rescue params[:id]
    entry = GeneralInventory.find(id)
#    raise params[:id].inspect
    if entry.is_a?(Array)
      print_string = ""
      (entry || []).each do |bottle|
        print_string += "#{Misc.create_bottle_label(bottle.drug_name,bottle.gn_identifier,bottle.expiration_date,bottle.received_quantity)}\n"
      end
    else
      print_string = Misc.create_bottle_label(entry.drug_name,entry.gn_identifier,entry.expiration_date, entry.received_quantity)
    end

    chars = ("a".."z").to_a  + ("0".."9").to_a
    rand_str = ""
    1.upto(7) { |i| rand_str << chars[rand(chars.size-1)] }
    send_data(print_string,:type=>"application/label; charset=utf-8", :stream=> false, :filename=>"#{rand_str}.lbl", :disposition => "inline")
  end
end

app/helpers/general_inventory_helper.rb
module GeneralInventoryHelper
end

app/views/general_inventory/_storeroom.html.erb
<div style="width: 100%; background-color: #006495;height: 4vh;text-align: center;color: white;padding-top: 1vh;">
  <span style="font-size: 1.5em;font-family: 'Arial Black', Gadget, sans-serif;">Transaction Trail</span>
</div>

<div style="height: 78vh; overflow: auto;width: 100vw; margin-left: auto;margin-right: auto;">
  <table id="generalInventory" class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead>
    <tr>
      <th>Date</th>
      <th style="width: 25%;">Issued To</th>
      <th style="width: 25%;">Issued By</th>
      <th style="width: 25%;">Amount Issued</th>
    </tr>
    </thead>

    <tbody>
    <% (@records || []).each do |issue| %>
        <tr>
          <td><%= issue.issue_date.strftime('%d %b, %Y') %></td>
          <td><%= issue.location_issued_to %></td>
          <td><%= issue.issuer %></td>
          <td style="text-align: right;padding-right: 1vw;"><%= number_with_delimiter(issue.quantity) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>


<div class="footer" >
  <button onmousedown="window.location = '/general_inventory/list?drug_id=<%= @item.drug_id %>'" class="nav-bttn green" style="margin-right: 1vw;float: right;">
    <%= t('forms.buttons.finish')%></button>
  <button onmousedown="window.location = '/issues/new?bottle=<%= @item.bottle_id %>'" class="nav-bttn" style="margin-right: 1vw;float: right;">
    Issue Item</button>
</div>

<div id="keypad">
  <span class="keypad"></span>
</div>


<%= javascript_include_tag 'jquery.dataTables.min.js' %>
<style type="text/css">
  .even{
    background-color: #CCCCCC !important;
  }
  input,label{
    margin-top: 3px;
    font-size: 1.7em;
  }

  th,td{
    font-size: 1.7em;
  }
</style>
<script type="text/javascript">
    // Styling the table with datatables library
    $(document).ready(function() {
        // $.fn.dataTable.moment( 'MMM-YYYY' );
        $('#generalInventory').DataTable({
            "bLengthChange": false,
            "bDestroy": true,
            "filter":false,
            "pageLength":5,
            "language": {
                "search": I18n.t('forms.labels.search'),
                "lengthMenu": "Display _MENU_ records per page",
                "zeroRecords": I18n.t('forms.labels.nothing_found'),
                "info": I18n.t('forms.labels.tbl_pages'),
                "infoEmpty": "No records available",
                "infoFiltered": I18n.t('forms.labels.filtered'),
                "oPaginate": {
                    "sNext": I18n.t('forms.buttons.next'),
                    "sPrevious": I18n.t('forms.buttons.previous')
                }
            }
        });} );


</script>

app/views/general_inventory/create.html.erb
<html>
<style>
    body{
        font-family: "Nimbus Sans L", "Arial Narrow", sans-serif;
    }


    <% if @show_next_button %>
    .page_button {
        display:block;
        font-size: 0.8em;
        color: black;
        background-color: lightgray;
        margin: 15px;
        border: 3px outset gray;
        -moz-user-select:none;
        width: 100px;
        height: 70px;
        text-align: center;
    }

    #filing_info {
        font-size:25px;
        -moz-user-select:none;
    }
    #patients_info_div{
        left:28px;
        position:absolute;
        top:0px;
        font-size:17;
        -moz-user-select:none;
    }
    td , th {
        text-align:center;
        border: 20px solid white;
        padding: 10px;
    }

    .filing_instraction {
        text-align:left;
    }

    .old_label {
        background-color:#FFFF99;
    }

    .new_label {
        background-color:lightgreen;
    }

    .active_heading {
        background-color:black;
        color:white;
    }

    #footer {
        background-color: #333333;
        bottom: 0;
        color: #CADCEA;
        height: 80px;
        overflow: hidden;
        padding-right: 20px;
        position: absolute;
        width: 98%;
    }

    <%end%>
</style>

<script>


    function done() {
        document.location = "<%=@redirect_url%>"
    }
</script>



<% if not @show_next_button %>
    <body>
    <br/><br/><br/>
    <center><h1><%=h @message %></h1></center>
    <iframe src="<%= @print_url %>" style='display:none'></iframe>
    </body>
    <script>
        setTimeout(redirect, 1000);
        function redirect(){
            document.location = '<%= @redirect_url %>'
        }
    </script>
<%else%>
    <body onload="setAttributes();">
    <%=@message%>
    <iframe src="/" style='display:none'></iframe>
    </body>
<%end%>
</html>

app/views/general_inventory/edit.html.erb
<script>
  var tt_cancel_destination = "/general_inventory";
  var tstCurrentDate = <%= Date.today.strftime("%d-%m-%Y") %>;

  function set_ajaxURL_for_suggestions(url, filter_value) {
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url + filter_value + "&search_string=");
    listSuggestions(tstCurrentPage);
  }
</script>


<%= form_for :general_inventory,  :url => edit_general_inventory_path  do |f| %>
    <table cellpadding=10>
      <tr>
        <td>
          Expiry Date:
        </td>
        <td>
          <%= text_field_tag 'expiry_date', @item.expiration_date.strftime("%d-%m-%Y"),
                             {:id => 'expiry_date',
                              :field_type => 'date',
                              :helpText => "Expiry date",
                              :maxDate => (Date.today + 20.year).to_date,
                              :minDate => Date.today.to_date,
                              :tt_pageStyleClass => "Date DatesOnly"} %>

        </td>
      </tr>
      <tr>
        <td>
          Amount Received:
        </td>
        <td>
          <input type="text" id="amount_received" name="amount_received" value=<%= @item.received_quantity %>
              field_type="number" helpText="<%= t('forms.labels.amount_received') %>" tt_pageStyleClass="NumbersOnly" />
        </td>
      </tr>
      <tr>
        <input type="hidden" value="<%= @item.gn_identifier%>" id="bottle_id" name="bottle_id" />
      </tr>
    </table>


    <%= submit_tag value="Submit"%>
<% end %>


<script>

  if(document.getElementById("date")) {

    document.getElementById("date").setAttribute("maxdate", (new Date((new Date()).setDate((new Date()).getDate() + 1000))));

    document.getElementById("date").setAttribute("mindate", (new Date((new Date()).setDate((new Date()).getDate() - 1))));

  }

</script>

app/views/general_inventory/index.html.erb
    <%= javascript_include_tag 'jquery.dataTables.min.js' %>
    <style type="text/css">
      .even{
        background-color: #CCCCCC !important;
      }
        input,label{
          margin-top: 3px;
          font-size: 1.7em;
        }

      th,td{
        font-size: 1.7em;
      }
    </style>
    <script type="text/javascript">
      // Styling the table with datatables library
      $(document).ready(function() {
        // $.fn.dataTable.moment( 'MMM-YYYY' );
        $('#generalInventory').DataTable({
          "bLengthChange": false,
          "bDestroy": true,
          "pageLength":5,
          "language": {
            "search": I18n.t('forms.labels.search'),
            "lengthMenu": "Display _MENU_ records per page",
            "zeroRecords": I18n.t('forms.labels.nothing_found'),
            "info": I18n.t('forms.labels.tbl_pages'),
            "infoEmpty": "No records available",
            "infoFiltered": I18n.t('forms.labels.filtered'),
            "oPaginate": {
              "sNext": I18n.t('forms.buttons.next'),
              "sPrevious": I18n.t('forms.buttons.previous')
            }
          }
        });
        search_box = $('#generalInventory').dataTable()
        search = document.getElementsByTagName("input")[0];
        search.setAttribute("id","search");
        document.getElementById('search').setAttribute("onclick","showKeyboard();");
        keyboard = document.getElementsByClassName("keypad")[0]
        showAlphaKeypad();
        setTimeout(initializeListener(), 3000);
      } );

      function initializeListener()
      {
        barcode = document.getElementById("search");
        barcode.focus();
        timerHand = setTimeout(function () {
          barcode.value = barcode.value.trim().replace(/\$/, "").replace(/\-/,"");
        }, 3000);

      }

    </script>
    <div style="height: 6vh;border: 1px inset black; border-width: 0px 0px 3px 0px;">
      <h1 style="margin-left: 0.5vw;"><%= "#{t('menu.terms.inventory')} (#{current_location.name})"%></h1>
    </div>

    <div style="height: 78vh; overflow: auto;width: 99vw; margin-left: auto;margin-right: auto;">
      <table id="generalInventory" class="table table-striped table-bordered" style="width: 98.5vw;" cellspacing="0">
        <thead>
        <tr>
          <th><%= t('menu.terms.item') %></th>
          <th style="width: 20%;"><%= t('menu.terms.category') %></th>
          <th style="width: 20%;"><%= t('menu.terms.current_quantity') %></th>
          <th style="width: 10%;"><%= t('menu.terms.actions') %></th>
        </tr>
        </thead>

        <tbody>
        <% (@inventory || []).each do |item| %>
            <tr>
              <td><%= item.drug_name.titleize rescue "" %></td>
              <td><%= item.drug_category_name %></td>
              <td style="text-align: right;padding-right: 1vw;"><%= number_with_delimiter(item.current_quantity) %></td>
              <td style="text-align: center;">
                <img style="" src="/assets/view_icon.png"  title="View item"
                     onmousedown="window.location='/general_inventory/list?drug_id=<%= item.drug_id %>'">
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="footer" >
      <button onmousedown="window.location = '/'" class="nav-bttn green" style="margin-right: 1vw;float: right;">
        <%= t('forms.buttons.finish')%></button>
      <button onmousedown="window.location = '/general_inventory/new'" class="nav-bttn blue"
              style="margin-right: 1vw;float: right;"><%= t('menu.terms.add_item')%></button>
    </div>

    <div id="keypad">
      <span class="keypad"></span>
    </div>

app/views/general_inventory/new.html.erb
<script>
  var tt_cancel_destination = "/";

  function set_ajaxURL_for_suggestions(url, filter_value) {
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url + filter_value + "&search_string=");
    listSuggestions(tstCurrentPage);
  }
</script>


<%= form_for :general_inventory,  :url => general_inventory_index_path  do |f| %>
    <table cellpadding=10>
      <tr>
        <td>Drug Category</td>
        <td>
          <select style='width: 100%;'  name='drug_category' id='drug_category' helptext="<%= t('forms.labels.drug_category')%>"
                  doublepane="false">
            <% (current_drug_categories || []).each do |option| %>
              <option value="<%= option%>"><%= option.titleize %></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td>
          <%= text_field_tag "drug_name", params[:drug_name],
                             {:id => 'drug_name',
                              :ajaxURL => '/drug/search?filter_value=',
                              :field_type => 'alpha',
                              :helpText => t('forms.labels.select_drug_name'),
                              :allowFreeText => false,
                              :tt_onLoad => "set_ajaxURL_for_suggestions('/drug/search?filter_value=' ,document.getElementById('drug_category').value);" } %>

        </td>
      </tr>
      <tr>
        <td>
          Expiry Date:
        </td>
        <td>
          <%= text_field_tag 'expiry_date', Date.today.strftime("%Y-%m-%d"),
                             {:id => 'expiry_date',
                              :field_type => 'date',
                              :helpText => t('forms.labels.expiry_date'),
                              :maxDate => (Date.today + 20.year).to_date,
                              :minDate => Date.today.to_date,
                              :tt_pageStyleClass => "Date DatesOnly"} %>

        </td>
      </tr>
      <tr>
        <td>
          Amount Received:
        </td>
        <td>
          <input type="text" id="amount_received" name="amount_received" value="" field_type="number"
                 helpText="<%= t('forms.labels.amount_received') %>" tt_pageStyleClass="NumbersOnly" />
        </td>
      </tr>
      <tr>
        <td>
          More Items
        </td>
        <td>
          <%= select_tag "more_items", options_for_select(['Yes', 'No'],  nil),
                         :class => 'input_cell', :helpText => t('forms.labels.more_items_of_type') , :required => true  %>

        </td>
      </tr>
      <tr>
        <td>
          Number of items:
        </td>
        <td>
          <%= text_field_tag "number_of_items", nil,
                             {:id => 'number_of_items',
                              :field_type => 'number',
                              :helpText => t('forms.labels.number_of_items'),
                              :condition => '$("more_items").value == "Yes"',
                              :tt_pageStyleClass=> "NumbersOnly"} %>

        </td>
      </tr>
    </table>


    <%= submit_tag value="Submit"%>
<% end %>


<script>

  if(document.getElementById("date")) {

    document.getElementById("date").setAttribute("maxdate", (new Date((new Date()).setDate((new Date()).getDate() + 1000))));

    document.getElementById("date").setAttribute("mindate", (new Date((new Date()).setDate((new Date()).getDate() - 1))));

  }

</script>

app/views/general_inventory/show.html.erb
<div style="border: 1px inset black; border-width: 0px 0px 3px 0px;padding-left: 0.5vw;height: 10vh;">
  <h2><%= "#{@item.drug_name.titleize}" %></h2>
  <div style="display: table-row; width: 100vw;margin-left: 0.5vw;font-size: 1.5em;">
    <div style="display: table-cell;width: 25vw;">
      <%= "#{t('menu.terms.bottle_id')} : #{Misc.dash_formatter(@item.bottle_id)}" %>
    </div>
    <div style="display: table-cell;width: 50vw;">
      <%= "#{t('forms.labels.drug_category')} : #{@item.drug_category}" %>
    </div>
    <% if current_location.name.match(/store/i) %>
        <div style="display: table-cell;font-size: 1.1em;">
          <%= "#{t('menu.terms.current_quantity')} : "%><span style='color:red;'><%= @item.current_quantity%></span>
        </div>
    <% end %>
  </div>
</div>

<% if current_location.name.match(/store/i) %>
    <%= render "/general_inventory/storeroom" %>
<% else %>
    <%= render "/general_inventory/dispensary" %>
<% end %>